version: '3.8'

services:
  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 skillswap.wsgi:application
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=skillswap
      - POSTGRES_USER=skillswap_user
      - POSTGRES_PASSWORD=skillswap_password

  redis:
    image: redis:6

  celery:
    build: .
    command: celery -A skillswap worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

  celery-beat:
    build: .
    command: celery -A skillswap beat --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db

volumes:
  postgres_data: