# Generated by Django 5.2.3 on 2025-06-21 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="skillexchange",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="skillexchange",
            name="meeting_type",
            field=models.CharField(
                choices=[
                    ("virtual", "Virtual Meeting"),
                    ("in_person", "In-Person Meeting"),
                ],
                default="virtual",
                max_length=20,
            ),
        ),
    ]
