# Generated by Django 5.2.3 on 2025-06-21 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0003_skillrequest_communicationsession"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillrequest",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Skill Request",
                "verbose_name_plural": "Skill Requests",
            },
        ),
        migrations.AlterUniqueTogether(
            name="skillrequest",
            unique_together=set(),
        ),
    ]
