# Generated by Django 5.2.3 on 2025-06-21 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0004_alter_skillrequest_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="skillrequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="communicationsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
