# Generated by Django 5.2.3 on 2025-06-22 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("skills", "0006_chatmessage_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.DeleteModel(
            name="ChatMessage",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
    ]
